#!/usr/bin/env python3
"""Vendor the portal's webfonts into the repo.

Both web and admin-client previously linked the Google Fonts stylesheet from
`index.html`. That link is render-blocking, and if fonts.googleapis.com is slow
or unreachable the page paints nothing at all until the request fails. This script
downloads the woff2 files and emits a local stylesheet instead.

Google serves these families as *variable* fonts: one file per (family, style)
covers the whole weight axis, so the naive "one file per weight" approach writes
22 rules pointing at 6 distinct files. This script keys on (family, style,
subset), writes one file per key, and declares the real weight range.

Usage:
    curl -A "<browser UA>" "<google fonts css2 url>" -o all.css
    python3 tools/vendor-fonts.py all.css <out-dir>

Writes <out-dir>/fonts.css and <out-dir>/fonts/*.woff2.
"""
import os
import re
import sys
import urllib.request
from collections import defaultdict

# Only these subsets are kept. The rest (cyrillic, greek, vietnamese) are dead
# weight for an English-language department portal.
KEEP = {"latin", "latin-ext"}

UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 1

    css_path, out_dir = sys.argv[1], sys.argv[2]
    css = open(css_path, encoding="utf-8").read()

    # Google emits `/* subset */` immediately before each @font-face block.
    blocks = re.findall(r"/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    if not blocks:
        print("no @font-face blocks found", file=sys.stderr)
        return 1

    # (family, style, subset) -> {weights, url, unicode-range}
    faces: dict[tuple[str, str, str], dict] = {}

    for subset, block in blocks:
        if subset not in KEEP:
            continue
        url_match = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not url_match:
            continue

        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        unicode_range = re.search(r"unicode-range:\s*([^;]+);", block)

        key = (family, style, subset)
        entry = faces.setdefault(
            key,
            {
                "weights": set(),
                "url": url_match.group(1),
                "unicode_range": unicode_range.group(1).strip() if unicode_range else None,
            },
        )
        entry["weights"].add(int(weight))
        # Every weight of one family/style resolves to the same variable file;
        # keep the first URL and confirm the rest agree.
        if entry["url"] != url_match.group(1):
            print(
                f"warning: {family} {style} {subset} has more than one file; "
                "expected a variable font",
                file=sys.stderr,
            )

    fonts_dir = os.path.join(out_dir, "fonts")
    os.makedirs(fonts_dir, exist_ok=True)

    def slug(text: str) -> str:
        return re.sub(r"[^a-z0-9]+", "", text.lower())

    rules = []
    for (family, style, subset), entry in sorted(faces.items()):
        low, high = min(entry["weights"]), max(entry["weights"])
        weight_value = str(low) if low == high else f"{low} {high}"
        name = f"{slug(family)}-{style}-{subset}.woff2"

        dest = os.path.join(fonts_dir, name)
        if not os.path.exists(dest):
            req = urllib.request.Request(entry["url"], headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = resp.read()
            with open(dest, "wb") as fh:
                fh.write(data)

        rule = [
            "@font-face {",
            f"  font-family: '{family}';",
            f"  font-style: {style};",
            f"  font-weight: {weight_value};",
            "  font-display: swap;",
            f"  src: url(./fonts/{name}) format('woff2');",
        ]
        if entry["unicode_range"]:
            rule.append(f"  unicode-range: {entry['unicode_range']};")
        rule.append("}")
        rules.append("\n".join(rule))

    header = (
        "/* Self-hosted webfonts.\n"
        " *\n"
        " * Generated by tools/vendor-fonts.py. Replace the stylesheet in\n"
        " * index.html with an import of this file rather than re-adding a Google\n"
        " * Fonts <link>: that link is render-blocking, so an unreachable or slow\n"
        " * fonts.googleapis.com delays or prevents first paint entirely.\n"
        " *\n"
        " * One file per family/style/subset. These are variable fonts, so a single\n"
        " * file covers the whole weight range declared above and the browser\n"
        " * fetches only the subsets a page actually renders.\n"
        " */\n"
    )

    with open(os.path.join(out_dir, "fonts.css"), "w", encoding="utf-8") as fh:
        fh.write(header + "\n".join(rules) + "\n")

    files = sorted(os.listdir(fonts_dir))
    total = sum(os.path.getsize(os.path.join(fonts_dir, f)) for f in files)
    print(f"{len(rules)} @font-face rules, {len(files)} files, {total / 1024:.0f} KB total")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())